{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jellyfin-pdb-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin-pdb-controller.labels" . | nindent 4 }}
  {{- $ann := merge (dict) .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- with $ann }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
